import turtle
'''
grd_num = int(input('학번을 입력하세요: '))
name = input('이름을 입력하세요: ')
hab = input('취미를 입력하세요: ')
print('-' *50)
print(' ' *10, '순천향재학교 메타버스&게임학과')
print('-' *50)
print('1. 학번:', grd_num)
print('2. 이름:', name)
print('3. 취미:', hab)

pi = 3.1415926535
print('%d' %pi)
print('%.1f' %pi)
print('%.2f' %pi)
print('%.3f' %pi)
print('%.4f' %pi)
print('%.5f' %pi)

print('## 택배를 보내기 위한 정보를 입력하세요. ##')
tape = input('받는 사람 : ')
adr = input('주소 : ')
wei = int(input('무게(g) : '))
print('** 받는 사람 ==>', tape)
print('** 주소 ==>', adr)
print('** 배송비 ==>', wei*5, '원')
'''
turtle.shape('turtle')
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(50)
turtle.forward(55)
turtle.left(50)
turtle.forward(5)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(100)
turtle.forward(60)
turtle.left(130)
turtle.forward(20)
turtle.right(30)
turtle.forward(30)
turtle.left(20)
turtle.forward(20)
turtle.left(40)
turtle.forward(40)
turtle.right(130)
turtle.forward(40)
turtle.left(40)
turtle.forward(20)
